Lizaya_Web/Lizaya_Web/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('', include('shops.urls')),

    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


Lizaya_Web/shops/urls.py
from django.urls import path
from . import views

app_name = 'shops'

urlpatterns = [
    path('', views.product_list, name='Home'),
    path('contact/', views.contact, name='Contact'),
    path('reach/', views.feedback, name='reach'),
    path('PortFolio/', views.folio, name='folio'),
    path('About/', views.about, name='about'),
    path('addfeatured/', views.AddFeatured, name='AddFeatured'),

]

Lizaya_Web/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('handlesignup/', views.handlesignup, name="handlesignup"),
    path('handlelogin/', views.handlelogin, name="handlelogin"),
    path('signup/', views.signup, name="signup"),
]

Lizaya_Web/shops/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=15, db_index=True)
    slug = models.SlugField(max_length=15, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shops:product_list_by_category', args=[self.slug])



class Contacts(models.Model):
    user_name = models.CharField(max_length=20, blank=False)
    email = models.EmailField()
    mobile_number = models.CharField(max_length=20, blank=True, null=True)
    message = models.TextField(max_length=100)
    submitted_date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('submitted_date',)

    def __str__(self):
        return self.user_name

    pass


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='media/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shops:product_detail', args=[self.id, self.slug])

class ProductFeatured(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, null=True, blank=True)
    text = models.CharField(max_length=220, null=True, blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.name


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=120, null=True, blank=True)
    email = models.EmailField()
    FIVE = '5'
    FOUR = '4'
    THREE = '3'
    TWO = '2'
    ONE = '3'
    NUM = (
        (FIVE, '5'),
        (FOUR, '4'),
        (THREE, '3'),
        (TWO, '2'),
        (ONE, '1')
    )
    stars = models.CharField(max_length=100, choices=NUM, default=FIVE)
    caption = models.CharField(max_length=120, null=True, blank=True)
    review = models.TextField()
    active = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name

# Create your models here.

Lizaya_Web/shops/forms.py
from django import forms
from django.forms.models import modelformset_factory
from .models import ProductFeatured

class ProductFeaturedForm(forms.ModelForm):
    class Meta:
        model = ProductFeatured
        fields  = [
            'product',
            'name',
            'text',
            'active',
        ]

Lizaya_Web/shops/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import *
from .models import Contacts


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)



def contact(request):
    if request.method == "GET":
        return render(request, 'electrical.html')
    elif request.method== "POST":
        try:
            name = request.POST['name']
            email = request.POST['email']
            mobile = request.POST['mobile']
            message = request.POST['message']
            contact = Contacts(user_name=name, email=email, mobile_number=mobile, message=message)
            contact.save()
            print("name = " + name)
            return render(request, 'electrical.html', {'success' : True})
        except Exception as e:
            print("error in request")
            return  render(request, 'electrical.html', {'success': False})

def feedback(request):
    return render(request, 'contact.html')

def folio(request):
    return render(request, 'portfolio.html')

def about(request):
    return render(request, 'about.html')


@login_required(login_url='../../login/')
def AddFeatured(request):
    name = 'Add Featured Product '
    form = ProductFeaturedForm(request.POST or None)
    context = {
        'name': name,
        'form': form
    }
    if request.method == 'POST':
        form = ProductFeaturedForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Featured Product Saved')
            return redirect('AddFeatured')
        else:
            messages.error(request, " Unsuccessfuly Adding Featured Product")
    else:
        return render(request, 'baseform.html', context)
# Create your views here.

# Create your views here.




# Create your views here.

Lizaya_Web/shops/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>josh enterprises</title>
     <meta name="description" content="This is the description">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    {% load static %}
        <link rel="stylesheet" href="{% static 'styles.css' %}"/>
 <script src="{% static 'cart.js' %}" async></script>
<style>
    ul li{
    float:left;
    text-align:center;
   width:180px;
   height:55px;
   background-color:black;
   line-height:40px;
   font-size:20px;
   margin-right:2px;
    border-radius:2px;
    box-shadow:0px 8px 16px 0px;
    transform:scale(0.9);
}

ul li a:hover{
   background-color:#48d1cc;
   opacity:-5px;
    border-radius:2px;
}

.top-right {
  position: absolute;
  right: 1px;
}
.top-left{
  position: absolute;
  top:260px;
  left:10px;

  }
ul li{
    float:left;
    text-align:center;
   width:180px;
   height:55px;
   background-color:#ff00ff;
   line-height:40px;
   font-size:20px;
   margin-right:0px;
    border-radius:2px;
    box-shadow:0px 8px 16px 0px;
    transform:scale(0.9);
}

.slide {
	float: left;
	position: absolute;
	opacity: 0;
	transition: opacity 3s linear;
}
 .modal{
         display:none;
         position:fixed;
         bottom:0;
         margin-right:10px;
         z-index:1;
         width:100%px;
         height:100%px;
         overflow:auto;
         background-color:rgb(0,0,0);
         background-color:rgba(0,0,0,0.4);
         padding-top:20px;
         }
  .modal-content{
         background-color:#fefefe;
         margin:10% auto 15% auto;
         border:1px solid #888;
         width:80%;
         float:left;
         align-items:center;
         margin-top:100px;

         }
</style>
</head>


<body>

<center><img src="{% static 'img/logo2.png' %}"height="90px"width="180px">
    <b><u><a style="color:black;font-size:50px;font-family:verdana;">Josh Classicals</a></u></b><br>
<i><b><a style="color:blue;font-size:20px;font-family:verdana;">For quality and affordable Services and Furniture products</a></b></i>
</center>

     <img src="{% static 'img/default/1.png' %}"height="220px" width="100%" alt="Bground" style="margin-top:auto">
<ul style="top:145px;position:absolute">
    <li style="background-color:#ff00ff;"><a href="{% url 'shops:Home' %}">Home</a></li>
    <li style="background-color:#ff00ff;"><a href="{% url 'shops:Contact' %}">Send Feedback</a></li>
    <li style="background-color:#ff00ff;"><a href="{% url 'shops:reach' %}">Contact Me</a></li>
    <li style="background-color:#ff00ff;"><a href="{% url 'shops:about' %}">About Me</a></li>
    <li style="background-color:#7fffd4"><a href="{% url 'shops:folio' %}">My PortFolio</a></li>


</ul>

<fieldset class="top-left"style="width:650px;height:60px;background-color:white">
    <legend style="color:blue;font-size:20px"><b>News and Notices</b></legend>
    <marquee ><b style="font-type:serif;font-size:15px">Welcome to my website! Reach me directly through my phone number or WhatsApp me through my phone for any Enquiry and assistance or you
    can still email me or write to me directly through my website</b></marquee>
</fieldset>

<div class=""style="right:10px;top:145px;margin-right:10px;position:absolute">
          <img src="{% static 'img/default/user_review.png' %}"height="50px"width="50px"onclick="document.getElementById('id01').style.display='block'">
    <br>
          {% if request.user.is_authenticated %}<a href="#" style="font-size:20px;">Welcome: <br>{{request.user}}
{% else %}Login
         </a>{% endif %}

    <div id="id01"class="modal"style="width:100%;height:100%;right:20px">
        <form method="post" class="modal-content animate"style="margin-left:160px;width:80%;margin-top:150px"action="{% url 'user:handlelogin'%}">
            {% csrf_token %}
            <div class="imgcontainer">
                <span onclick="document.getElementById('id01').style.display='none'"
class="close"title="close Modal">&times;</span>
                <img src="{% static 'img/default/user_review.png' %}"height="60"width="60" alt="Avatar">
            </div>
            <div class="login">
                <label><b>Enter Username:</b></label><br>
                <input type="text" id="input" placeholder="Enter Your Name"name="uname" required>
                 <label class="control-label" for="input"></label><i class="mtrl-select"></i>
               <br>
                <label><b>Enter Password</b></label><br>
                <input type="password"placeholder="Enter Password"name="password1"required>
                 <label class="control-label" for="input"></label><i class="mtrl-select"></i>
               <br>
                <button class="mtr-btn signin"type="submit"style="margin:8px 0;padding:14px 20px;background-color:#48d1cc;color:white;border:block">Login</button><br>
                <input type="checkbox"checked="checked"style="margin-top:10px;margin-bottom:10px">Remember Me
                <p>Don't have an account?
                <br><button style="background-color:pink;width:90px;height:40px"><a href="{% url 'user:signup' %}" style="font-size:13px">Register</a></button></p>

            </div>
            <div class="login"style="background-color:#f1f1f1">
                <button type="button"onclick="document.getElementById('id01').style.display='none'"
                        class="cancelbtn">Cancel</button>
                <span class="psw">Forgot
                    <a href="#">Password?</a>
                </span>
            </div>
        </form>
    </div>
     <div class="cd-cart cd-cart--empty js-cd-cart top-right"style="float:right;top:102px;position:absolute">
         <button style="cursor:pointer;height:50px;width:80px"class="section-header btn-primary "onclick="document.getElementById('josh')
                   .style.display='block'">CART<br>
             <span class="glyphicon glyphicon-shopping-cart my-cart-icon"style=""><span class="badge badge-notify my-cart-badge"style="background-color:#00ff00">0</span> </span></button>
		  <div id="josh" class="undisputed"style="width:850px;background-color:#ADD8E6">
               <div class="cart-row"style="width:850px;background-color:#3ADD8E6">
                <span onclick="document.getElementById('josh')
                    .style.display='none'"
                               class="close"title="Close Modal">&times;</span>
               <span class="cart-item cart-header cart-column"><u>ITEM</u></span>
               <span class="cart-price cart-header cart-column"><u>PRICE</u></span>
               <span class="cart-quantity cart-header cart-column"><u>QUANTITY</u></span>
            </div>
                <div class="cart-items"style="background-color:3ADD8E6">
            </div>
            <div class="cart-total">
                <strong class="cart-total-title">Total Price:</strong>
                <span class="cart-total-price"><b>Ksh0</b></span>
                <a href=""class="checkout btn"required="please select products">Checkout</a>
            </div>
          </div>
     </div></div>





            <hr style="font-size:20px">



    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}

    {% endblock %}

<footer class="footer"style="background-color:#ADD8E6;border-radius:5px;padding-top:15px">
         <div class="column">
      <p class="text-sm">Need support? Call <span class="text-primary">+254 715 782 132</span></p>
      <div class="social-bar text-center space-bottom">
        <a href="#" class="sb-skype" data-toggle="tooltip" data-placement="top" title="Skype">
          <i class="socicon-skype"></i>
        </a>
        <a href="#" class="sb-facebook" data-toggle="tooltip" data-placement="top" title="Facebook">
          <i class="socicon-facebook"></i>
        </a>
        <a href="#" class="sb-google-plus" data-toggle="tooltip" data-placement="top" title=""
          data-original-title="Google+">
          <i class="socicon-googleplus"></i>
        </a>
        <a href="#" class="sb-twitter" data-toggle="tooltip" data-placement="top" title="Twitter">
          <i class="socicon-twitter"></i>
        </a>
        <a href="#" class="sb-instagram" data-toggle="tooltip" data-placement="top" title=""
          data-original-title="Instagram">
          <i class="socicon-instagram"></i>
        </a>
      </div></div>
    <div class="column">
      <h3 class="widget-title">
        Subscription
        <small>To receive latest offers and discounts from the shop.</small>
      </h3>
      <form action="." class="subscribe-form" novalidate>
        <input type="email" class="form-control" name="EMAIL" placeholder="Your e-mail">

        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"
            name="b_c7103e2c981361a6639545bd5_1194bb7544" tabindex="-1" value=""></div>
        <button type="submit"><i style="padding-top:8px;" class="material-icons send"></i></button>
      </form>
    </div>
    <div class="column">
      <h3 class="widget-title">
        Payment Methods
        <small>We support one of the following payment methods.</small>
      </h3>
      <div class="cards"><img src="{% static 'img/cards.png'%}" alt="Cards">Mpesa</div>

      <div class="scroll-to-top-btn"><i class="material-icons trending_flat"></i></div>
    </div>
    </footer><!-- footer -->
<hr style="background-color:blue">
<center>
  <footer class="page-footer font-small black">
	  <div class="footer-copyright text-center py-3"style="font-size:18px">Developed by Owino Technologies © {% now "Y" %}
	  <br><small class="text-muted">All rights reserved!</small>
	</div>
	</footer>
</center>
  <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/vendor/smoothscroll.js' %}"></script>
  <script src="{% static 'js/vendor/velocity.min.js' %}"></script>
  <script src="{% static 'js/vendor/waves.min.js' %}"></script>
  <script src="{% static 'js/vendor/icheck.min.js' %}"></script>
  <script src="{% static 'js/vendor/nouislider.min.js' %}"></script>
  <script src="{% static 'js/scripts.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>