Lizaya_Web/Lizaya_Web/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('', include('shops.urls')),

    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


Lizaya_Web/shops/urls.py
from django.urls import path
from . import views

app_name = 'shops'

urlpatterns = [
    path('', views.product_list, name='Home'),
    path('contact/', views.contact, name='Contact'),
    path('reach/', views.feedback, name='reach'),
    path('PortFolio/', views.folio, name='folio'),
    path('About/', views.about, name='about'),
    path('addfeatured/', views.AddFeatured, name='AddFeatured'),

]

Lizaya_Web/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('handlesignup/', views.handlesignup, name="handlesignup"),
    path('handlelogin/', views.handlelogin, name="handlelogin"),
    path('signup/', views.signup, name="signup"),
]

Lizaya_Web/user/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(default=0)
    phone = models.CharField(max_length=14)
    cover_photos = models.ImageField(default='cover3.jpeg', upload_to='cover_pics')
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.username} Profile'

Lizaya_Web/user/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login as dj_login
from django.http.response import JsonResponse, HttpResponse
from django.contrib.auth import authenticate, logout
from django.contrib import messages, auth


def signup(request):
    return render(request, "register.html")


# view for rendering login page
def login(request):
    return render(request, "login.html")


def handlesignup(request):
    if request.method == 'POST':
        # get the post parameters
        username = request.POST["uname"]
        fname = request.POST["fname"]
        lname = request.POST["lname"]
        phone = request.POST["phone"]
        email = request.POST["email"]
        password1 = request.POST["password1"]
        password2 = request.POST["password2"]
        # check for errors in input
        if request.method == 'POST':
            try:
                user_exists = User.objects.get(username=request.POST['uname'])
                messages.error(
                    request, " Username already taken, Try another username!!!")
                return redirect("/signup")
            except User.DoesNotExist:
                if len(username) > 15:
                    messages.error(
                        request, " Username must be max 15 characters, Please try again")
                    return redirect("/signup")
                if not username.isalnum():
                    messages.error(
                        request, " Username should only contain letters and numbers, Please try again")
                    return redirect("/signup")
                if password1 != password2:
                    messages.error(
                        request, " Password do not match, Please try again")
                    return redirect("/signup")
        # create the user
        user = User.objects.create_user(username, email, password1)
        user.first_name = fname
        user.last_name = lname
        user.phone = phone
        user.save()
        messages.success(
            request, " Your account has been successfully created<br>Please login below")
        return redirect("shops:Home")
    else:
        return HttpResponse('signup')


# view for rendering data from login page
def handlelogin(request):
    if request.method == 'POST':
        # get the post parameters
        name = request.POST["uname"]
        password = request.POST["password1"]
        user = authenticate(username=name, password=password)
        # cheching for valid login
        if user is not None:
            dj_login(request, user)
            messages.success(request, "")
            return redirect("shops:Home")
        else:
            messages.error(request, " Invalid Credentials, Please try again")
            return redirect("user:signup")



# view for rendering logout
def handlelogout(request):
    logout(request)
    messages.success(request, " Successfully logged out")
    return redirect('/')

Lizaya_Web/user/templates/login.html
{% load static %}
 <html lang="en">
 <head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="https://storage.googleapis.com/bytewalk/icon.png"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
      <link rel="stylesheet" href="{% static 'css/strip.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
     <link rel="stylesheet" href="{% static 'css/style.css' %}">
<style>
    .btn {
    text-align: center;
    vertical-align: middle;
    padding:.67em .67em;
    cursor: pointer;
}

.btn-primary {
    color: white;
    background-color: #56CCF2;
    border: none;
    border-radius: .3em;
    font-weight: bold;
    width:80px;
}
.btn-primary:hover {
    background-color: #2D9CDB;
}
.shop-item {
    margin:0;
    border-style:none;
}
.shop-details{
     text-align: center;
     left:0;
     right:0;
}
.btn-info{
  background-color:pink;
   text-align: center;
    vertical-align: middle;
    padding:.67em .67em;
    cursor: pointer;
}
.shop-item-title {
    width:70%;
    text-align: center;
    font-weight: bold;
    font-size: 1.5em;
    color:black;
}

.shop-item-details {
      display: flex;
    align-items: center;
    margin-bottom:2px;
    margin-top:2px;

}

.btn-danger {
    color: white;
    background-color: #EB5757;
    border: none;
    border-radius: .3em;
    font-weight: bold;
    width:70px;
    height:25px;
    text-align:center;
}

.btn-danger:hover {
    background-color: #CC4C4C;
}

.checkout {
    display: block;
    margin: 40px auto 80px auto;
    font-size: 1.75em;
}
.search-box {
  background: var(--mainPink);
  color: var(--mainBlack);
}
.badge{
   background-color:red;
   border-radius:10px;
   color:white;
   display:inline-block;
   font-size:12px;
   line-height:1;
   padding:3px 7px;
   text-align:center;
   white-space:nowrap;
   }
 .shop-item-title {
      display: block;
      padding-top:0px;
      font-size:18px;
    }


   ul{
   margin:0px;
   padding:0px;
   list-style:none;
}
ul li{
    float:left;
    text-align:center;
   width:180px;
   height:55px;
   background-color:#ff00ff;
   line-height:40px;
   font-size:20px;
   margin-right:0px;
    border-radius:2px;
    box-shadow:0px 8px 16px 0px;
    transform:scale(0.9);
}
ul li a{
   text-decoration:none;
   color:white;
   display:block;
   border-style:0;
}

ul li a:hover{
   background-color:#48d1cc;
   opacity:-5px;
    border-radius:2px;
}
ul li ul li{
   float:right;
   display:none;
}
ul li:hover ul li{
  display:block;
}
input[type=text],
input[type=password]{
 width:90%;
 height:37px;
 display:inline-block;
 border:3px solid #00B4CC;
 box-sizing:border-box;
}

 .cancelbtn{
         width:auto;
         padding:10px 18px;
         background-color:red;
         }
 .imgcontainer{
         text-align:center;
         margin:19px 0 12px 0;
         position:relative;
         }
 .login{
         padding:none;
         top:0;
         align-items:center;
         }
 span.button{
         width:auto;
         float:right;
         padding:10px 20px;
         background-color:blue;
         }
  span.psw{
    float:right;
    padding-top:16px;
  }
  .modal{
         display:none;
         position:absolute;
         bottom:0;
         margin-right:0;
         z-index:1;
         width:100%px;
         height:100%px;
         overflow:auto;
         background-color:rgb(0,0,0);
         background-color:rgba(0,0,0,0.4);
         padding-top:20px;
         float:left;
         }
  .modal-content{
      background-color:#fefefe;
         margin:10% auto 15% auto;
         border:1px solid #888;
         width:80%;
         align-items:center;
         margin-top:100px;

         }

  .close{
         position:absolute;
         right:25px;
         top:0;
         color:#000;
         font-size:35px;
         font-weight:bold;
         transition:0.3s;
         }
 .close:hover,
 .close:focus{
         color:red;
         cursor:pointer;}
.animate{
         -webkit-animation:animate zoom 0.6s;
         animation:animate zoom 0.6s}
         @-webkit-keyframes animate zoom{
         from{-webkit-transform:scale(0)}
         to{-webkit-transform:scale(1)}
         }
 @keyframes animatezoom{
         from{transform:scale(0)}
         to{transform:scale(1)}
         }
         @media screen and(max-width:300px)
         span.psw{
         display:block;
         float:none;
         align:left;
         }

a.lightbox img {
height: 300px;
border: 3px solid white;
box-shadow: 0px 0px 8px rgba(0,0,0,.3);
margin: 94px 20px 20px 20px;
}

/* Styles the lightbox, removes it from sight and adds the fade-in transition */

.lightbox-target {
position: fixed;
width:90%;
top:0;
right:0;
background:green;
opacity:0;
-webkit-transition: opacity .5s ease-in-out;
-moz-transition: opacity .5s ease-in-out;
-o-transition: opacity .5s ease-in-out;
transition: opacity .5s ease-in-out;
overflow: hidden;
 border-radius:10px;
  box-shadow:0 0 0 10px pink;
 transform:scale(1.0);
}

/* Styles the lightbox image, centers it vertically and horizontally, adds the zoom-in transition and makes it responsive using a combination of margin and absolute positioning */

.lightbox-target img {
margin: auto;
position:absolute;
top: 0;
left:0;
right:0;
bottom: 0;
width:85%;
height:80%;
max-height: 0%;
max-width: 0%;
border: 3px solid white;
box-shadow: 0px 0px 8px rgba(0,0,0,.3);
box-sizing: border-box;
-webkit-transition: .5s ease-in-out;
-moz-transition: .5s ease-in-out;
-o-transition: .5s ease-in-out;
transition: .5s ease-in-out;
 border-radius:10px;
  box-shadow:0 0 0 10px green;
 transform:scale(1.0);
}

/* Styles the close link, adds the slide down transition */

a.lightbox-close {
display:block;
width:45px;
height:45px;
box-sizing: border-box;
background:red;
color: black;
text-decoration: none;
position: absolute;
right: 0;
-webkit-transition: .5s ease-in-out;
-moz-transition: .5s ease-in-out;
-o-transition: .5s ease-in-out;
transition: .5s ease-in-out;
}
/* Provides part of the "X" to eliminate an image from the close link */

a.lightbox-close:before {
content: "";
display: block;
height:27px;
width: 1px;
background: black;
position: absolute;
left: 26px;
top:10px;
-webkit-transform:rotate(45deg);
-moz-transform:rotate(45deg);
-o-transform:rotate(45deg);
transform:rotate(45deg);
}

/* Provides part of the "X" to eliminate an image from the close link */

a.lightbox-close:after {
content: "";
display: block;
height:0px;
width: 0px;
background: black;
position: absolute;
left: 26px;
top:10px;
-webkit-transform:rotate(-45deg);
-moz-transform:rotate(-45deg);
-o-transform:rotate(-45deg);
transform:rotate(-45deg);
}

  .my-cart-icon-affix {
    position: fixed;
    z-index: 999;
  }
.section-header{
    float:right;
    right:0px;
    margin-top:0px;
    font-family: "Metal Mania";
    font-weight: normal;
    text-align: center;
    font-size: 1.5em;
}


.btn-danger {
    color: white;
    background-color: #EB5757;
    border: none;
    border-radius: .3em;
    font-weight: bold;
}

.btn-danger:hover {
    background-color: #CC4C4C;
}

 #s-cover:hover #s-circle
 {
    top:-1px;
    width:67px;
    height:15px;
    border-width:0;
    background-color:#fff;
    border-radius:20px;
 }
 #s-cover:hover .span{
    top:50%;
    left:56px;
    width:25px;
    margin-top:-9px;
    transform:rotateZ(0);
 }
 #s-cover:hover .span:before{
    bottom:11px;
    transform:rotateZ(-52deg);
 }
 #s-cover:hover .span:after{
    bottom:-11px;
    transform:rotateZ(-52deg);
 }
 #s-cover:hover .span:before,#s-cover:hover .span:after
 {
    right:-6px;
    width:40px;
    background-color:#fff;
 }
.btn-info{
   padding:10px;
   font-size:16px;
   border:none;
   cursor:pointer;
}

@import url(https://fonts.googleapis.com/css?family=open+Sans);
.wrap{
font-family:'open Sans',sans-serif;
 width:550px;
 left:30%;
 right:30%
 transform:translate(-50%, -50%);
}


</style>
 </head>
 <body style="">

 <center><div>
 <img src="{% static 'img/logo2.png' %}" height="250px"width="450px"/><br>
 <a href="" class=""style="color:red;font-size:30px;margin-top:10px;"><b>Welcome to Josh Classicals</b><br></a></div></center>
 <center><p style="font-size:29px"><i><b>This is a personal online platform meant to showcase my work and services that i personally offer
 <br>and at the same time allow my clients to make their furniture purchases online or purchase my services.</b></i></p></center>

<br />

{% for messages in message %}
{% endfor %}
           <center> <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="login-reg-bg">
                    <div class="log-reg-area sign">
                        <fieldset style="width:500px">
                            <legend>
                                <h2 class="log-title">Login</h2></legend>
                         {% for message in messages %}
                      <h3>{{message}}</h3>
                  {% endfor %}
                        <form method="post" action="{% url 'user:handlelogin'%}">
                            {% csrf_token %}
                            <div class="form-group">Username:<br>
                                <input type="text" id="input" name="uname" required="required"/>
                                <label class="control-label" for="input"></label><i class="mtrl-select"></i>
                            </div>
                            <div class="form-group">Password:<br>
                                <input type="password" name="password1" required="required"/>
                                <label class="control-label" for="input"></label><i class="mtrl-select"></i>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" checked="checked"/><i class="check-box"></i>Always Remember
                                    Me.
                                </label>
                            </div>
                            <a href="" title="password reset" class="forgot-pwd">Forgot Password?</a>
                            <div class="submit-btns">
                                <button class="mtr-btn signin" type="submit"><span>Login</span></button><br>
                                <p style="margin-top:15px;margin-bottom:15px;padding-bottom:15px"><b>Or<br>
                                <a class="mtr-btn signup" href="{% url 'user:signup' %}"type="signup" style="margin-top:15px;color:green"><span>Register</span>
                                </a><br>if You Don't Have An Account </b></p>
                            </div> <a href="{% url 'shops:Home' %}"><b>Back Home</b></a>
                        </form>
                        </fieldset></div>
                </div>

           </div>
                <footer class="page-footer font-small black">
	  <div class="footer-copyright text-center py-3">Undisputed Josh © {% now "Y" %}
	  <br><small class="text-muted">All rights reserved!</small>
	</div>
	</footer>
           </center></body></html>

Lizaya_Web/user/templates/register.html
{% load static %}
 <html lang="en">
 <head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="https://storage.googleapis.com/bytewalk/icon.png"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
      <link rel="stylesheet" href="{% static 'css/strip.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
     <link rel="stylesheet" href="{% static 'css/style.css' %}">
<style>
    .btn {
    text-align: center;
    vertical-align: middle;
    padding:.67em .67em;
    cursor: pointer;
}

.btn-primary {
    color: white;
    background-color: #56CCF2;
    border: none;
    border-radius: .3em;
    font-weight: bold;
    width:80px;
}
.btn-primary:hover {
    background-color: #2D9CDB;
}
.shop-item {
    margin:0;
    border-style:none;
}
.shop-details{
     text-align: center;
     left:0;
     right:0;
}
.btn-info{
  background-color:pink;
   text-align: center;
    vertical-align: middle;
    padding:.67em .67em;
    cursor: pointer;
}
.shop-item-title {
    width:70%;
    text-align: center;
    font-weight: bold;
    font-size: 1.5em;
    color:black;
}

.shop-item-details {
      display: flex;
    align-items: center;
    margin-bottom:2px;
    margin-top:2px;

}

.btn-danger {
    color: white;
    background-color: #EB5757;
    border: none;
    border-radius: .3em;
    font-weight: bold;
    width:70px;
    height:25px;
    text-align:center;
}

.btn-danger:hover {
    background-color: #CC4C4C;
}

.checkout {
    display: block;
    margin: 40px auto 80px auto;
    font-size: 1.75em;
}
.search-box {
  background: var(--mainPink);
  color: var(--mainBlack);
}
.badge{
   background-color:red;
   border-radius:10px;
   color:white;
   display:inline-block;
   font-size:12px;
   line-height:1;
   padding:3px 7px;
   text-align:center;
   white-space:nowrap;
   }
 .shop-item-title {
      display: block;
      padding-top:0px;
      font-size:18px;
    }


   ul{
   margin:0px;
   padding:0px;
   list-style:none;
}
ul li{
    float:left;
    text-align:center;
   width:180px;
   height:55px;
   background-color:#ff00ff;
   line-height:40px;
   font-size:20px;
   margin-right:0px;
    border-radius:2px;
    box-shadow:0px 8px 16px 0px;
    transform:scale(0.9);
}
ul li a{
   text-decoration:none;
   color:white;
   display:block;
   border-style:0;
}

ul li a:hover{
   background-color:#48d1cc;
   opacity:-5px;
    border-radius:2px;
}
ul li ul li{
   float:right;
   display:none;
}
ul li:hover ul li{
  display:block;
}
input[type=text],
input[type=password]{
 width:90%;
 height:37px;
 display:inline-block;
 border:3px solid #00B4CC;
 box-sizing:border-box;
}

 .cancelbtn{
         width:auto;
         padding:10px 18px;
         background-color:red;
         }
 .imgcontainer{
         text-align:center;
         margin:19px 0 12px 0;
         position:relative;
         }
 .login{
         padding:none;
         top:0;
         align-items:center;
         }
 span.button{
         width:auto;
         float:right;
         padding:10px 20px;
         background-color:blue;
         }
  span.psw{
    float:right;
    padding-top:16px;
  }
  .modal{
         display:none;
         position:absolute;
         bottom:0;
         margin-right:0;
         z-index:1;
         width:100%px;
         height:100%px;
         overflow:auto;
         background-color:rgb(0,0,0);
         background-color:rgba(0,0,0,0.4);
         padding-top:20px;
         float:left;
         }
  .modal-content{
      background-color:#fefefe;
         margin:10% auto 15% auto;
         border:1px solid #888;
         width:80%;
         align-items:center;
         margin-top:100px;

         }

  .close{
         position:absolute;
         right:25px;
         top:0;
         color:#000;
         font-size:35px;
         font-weight:bold;
         transition:0.3s;
         }
 .close:hover,
 .close:focus{
         color:red;
         cursor:pointer;}
.animate{
         -webkit-animation:animate zoom 0.6s;
         animation:animate zoom 0.6s}
         @-webkit-keyframes animate zoom{
         from{-webkit-transform:scale(0)}
         to{-webkit-transform:scale(1)}
         }
 @keyframes animatezoom{
         from{transform:scale(0)}
         to{transform:scale(1)}
         }
         @media screen and(max-width:300px)
         span.psw{
         display:block;
         float:none;
         align:left;
         }

a.lightbox img {
height: 300px;
border: 3px solid white;
box-shadow: 0px 0px 8px rgba(0,0,0,.3);
margin: 94px 20px 20px 20px;
}

/* Styles the lightbox, removes it from sight and adds the fade-in transition */

.lightbox-target {
position: fixed;
width:90%;
top:0;
right:0;
background:green;
opacity:0;
-webkit-transition: opacity .5s ease-in-out;
-moz-transition: opacity .5s ease-in-out;
-o-transition: opacity .5s ease-in-out;
transition: opacity .5s ease-in-out;
overflow: hidden;
 border-radius:10px;
  box-shadow:0 0 0 10px pink;
 transform:scale(1.0);
}

/* Styles the lightbox image, centers it vertically and horizontally, adds the zoom-in transition and makes it responsive using a combination of margin and absolute positioning */

.lightbox-target img {
margin: auto;
position:absolute;
top: 0;
left:0;
right:0;
bottom: 0;
width:85%;
height:80%;
max-height: 0%;
max-width: 0%;
border: 3px solid white;
box-shadow: 0px 0px 8px rgba(0,0,0,.3);
box-sizing: border-box;
-webkit-transition: .5s ease-in-out;
-moz-transition: .5s ease-in-out;
-o-transition: .5s ease-in-out;
transition: .5s ease-in-out;
 border-radius:10px;
  box-shadow:0 0 0 10px green;
 transform:scale(1.0);
}

/* Styles the close link, adds the slide down transition */

a.lightbox-close {
display:block;
width:45px;
height:45px;
box-sizing: border-box;
background:red;
color: black;
text-decoration: none;
position: absolute;
right: 0;
-webkit-transition: .5s ease-in-out;
-moz-transition: .5s ease-in-out;
-o-transition: .5s ease-in-out;
transition: .5s ease-in-out;
}
/* Provides part of the "X" to eliminate an image from the close link */

a.lightbox-close:before {
content: "";
display: block;
height:27px;
width: 1px;
background: black;
position: absolute;
left: 26px;
top:10px;
-webkit-transform:rotate(45deg);
-moz-transform:rotate(45deg);
-o-transform:rotate(45deg);
transform:rotate(45deg);
}

/* Provides part of the "X" to eliminate an image from the close link */

a.lightbox-close:after {
content: "";
display: block;
height:0px;
width: 0px;
background: black;
position: absolute;
left: 26px;
top:10px;
-webkit-transform:rotate(-45deg);
-moz-transform:rotate(-45deg);
-o-transform:rotate(-45deg);
transform:rotate(-45deg);
}

  .my-cart-icon-affix {
    position: fixed;
    z-index: 999;
  }
.section-header{
    float:right;
    right:0px;
    margin-top:0px;
    font-family: "Metal Mania";
    font-weight: normal;
    text-align: center;
    font-size: 1.5em;
}


.btn-danger {
    color: white;
    background-color: #EB5757;
    border: none;
    border-radius: .3em;
    font-weight: bold;
}

.btn-danger:hover {
    background-color: #CC4C4C;
}

 #s-cover:hover #s-circle
 {
    top:-1px;
    width:67px;
    height:15px;
    border-width:0;
    background-color:#fff;
    border-radius:20px;
 }
 #s-cover:hover .span{
    top:50%;
    left:56px;
    width:25px;
    margin-top:-9px;
    transform:rotateZ(0);
 }
 #s-cover:hover .span:before{
    bottom:11px;
    transform:rotateZ(-52deg);
 }
 #s-cover:hover .span:after{
    bottom:-11px;
    transform:rotateZ(-52deg);
 }
 #s-cover:hover .span:before,#s-cover:hover .span:after
 {
    right:-6px;
    width:40px;
    background-color:#fff;
 }
.btn-info{
   padding:10px;
   font-size:16px;
   border:none;
   cursor:pointer;
}

@import url(https://fonts.googleapis.com/css?family=open+Sans);
.wrap{
font-family:'open Sans',sans-serif;
 width:550px;
 left:30%;
 right:30%
 transform:translate(-50%, -50%);
}


</style>
 </head>
 <body style="">

 <center><div>
 <img src="{% static 'img/logo2.png' %}" height="250px"width="450px"/><br>
 <a href="" class=""style="color:red;font-size:30px;margin-top:10px;"><b>Welcome to Josh Classicals</b><br></a></div></center>
 <center><p style="font-size:29px"><i><b>This is a personal online platform meant to showcase my work and services that i personally offer
 <br>and at the same time allow my clients to make their furniture purchases online or purchase my services.</b></i></p></center>
{% block content %}
<br />

           <div class="container my-4 bg pb-5">
    <div class="row justify-content-center ">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <center><h1>Create an Account</h1></center>
                    <div class="messages" id="alert-message">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button></div> {% endfor %}</div>
                  <center> <fieldset style="width:650px">
                        <legend style="font-size:30px"><b><i>Fill the form below:</i></b></legend>
                    <form method="post" class="modal-content animate" action="{% url 'user:handlesignup' %}">
                         {% csrf_token %}
                        <div class="login">
                            <label for="uname"style="font-size:25px">Enter Username</label><br>
                            <input type="text" class="form-control" id="uname" placeholder="Enter your Nickname"
                                name="uname" required>
                        </div>
                        <div class="form-group">
                            <label for="name"style="font-size:25px">Enter First Name</label><br>
                            <input type="text" class="form-control" id="fname" placeholder="Enter your First Name"
                                name="fname" required>
                        </div>
                        <div class="form-group">
                            <label for="name"style="font-size:25px">Enter Last Name</label><br>
                            <input type="text" class="form-control" id="lname" placeholder="Enter your Last Name"
                                name="lname" required><br>

                            <label for="phone"style="font-size:25px">Your Phone</label><br>
                            <input type="text"class="form-control" id="phone" placeholder="Enter your Phone e.g 07xxxxxxxx"
                                name="phone" required><br>

                            <label for="email"style="font-size:25px">Your Email</label><br>
                            <input type="text" class="form-control" id="email" placeholder="Enter your Email"
                                name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="password"style="font-size:25px">Password</label><br>
                            <input type="password" class="form-control" id="password1" placeholder="Choose a password"
                                name="password1" required>
                        </div>
                        <div class="form-group">
                            <label for="password2"style="font-size:25px">Confirm password</label><br>
                            <input type="password" class="form-control" id="password2"
                                placeholder="Retype your password" name="password2" required>
                        </div>
                        <button type="submit" class="btn btn-primary mt-2"style="height:50px">SignUp</button></form>
                   <center>     <p class="text-center"style="margin-top:10px;font-size:18px">
                Already Registered!
                <a href="{% url 'user:login' %}"><b>Login Now!</b></a>
                </p></center>
            <h3 align="center">
    <font color="#6495ed" face="chiller">
        {{ message }}
    </font>
</h3>
                  </fieldset></center></div>

            </div>
        </div>
    </div>
</div>

     <center><footer class="page-footer font-small black">
	  <div class="footer-copyright text-center py-3">Undisputed Josh © {% now "Y" %}
	  <br><small class="text-muted">All rights reserved!</small>
	</div>
     </footer></center>

 {% endblock content %}</body></html>